Fix trace test (#3336)
The test was failing on Ruby 2.3, due to how truncate was used.
ArgumentError: wrong number of arguments (given 1, expected 0)