Wrong Example...
```
irb(main):001:0> require "google/cloud/logging"
=> true
irb(main):002:0>
irb(main):003:0* logging = Google::Cloud::Logging.new
NoMethodError: undefined method `new' for Google::Cloud::Logging:Module
	from (irb):3
	from /usr/local/bin/irb:11:in `<main>'```