Address these two failures of `google-cloud-storage/test/google/cloud/storage/project_anonymous_test.rb`
Because object of `Object` class does not have `_` method defined
It is owned by `Minitest::Spec::DSL::InstanceMethods`.

Refer https://github.com/rubocop-hq/rubocop-minitest/issues/68#issuecomment-599200113

```
% bundle exec ruby -w -Itest test/google/cloud/storage/project_anonymous_test.rb -n /test_0001_raises\|test_0002_raises/
... snip ...

FF

Finished in 0.002656s, 753.0120 runs/s, 753.0120 assertions/s.

  1) Failure:
Google::Cloud::Storage::Project::anonymous::mock_storage#test_0002_raises when listing buckets without authentication [test/google/cloud/storage/project_anonymous_test.rb:41]:
[Google::Cloud::UnauthenticatedError] exception expected, not
Class: <NoMethodError>
Message: <"undefined method `_' for #<Object:0x00007fae26010460>">
---Backtrace---
test/google/cloud/storage/project_anonymous_test.rb:36:in `list_buckets'
/Users/yahonda/src/github.com/googleapis/google-cloud-ruby/google-cloud-storage/lib/google/cloud/storage/service.rb:76:in `block in list_buckets'
/Users/yahonda/src/github.com/googleapis/google-cloud-ruby/google-cloud-storage/lib/google/cloud/storage/service.rb:631:in `execute'
/Users/yahonda/src/github.com/googleapis/google-cloud-ruby/google-cloud-storage/lib/google/cloud/storage/service.rb:75:in `list_buckets'
/Users/yahonda/src/github.com/googleapis/google-cloud-ruby/google-cloud-storage/lib/google/cloud/storage/project.rb:153:in `buckets'
test/google/cloud/storage/project_anonymous_test.rb:41:in `block (3 levels) in <main>'
---------------

  2) Failure:
Google::Cloud::Storage::Project::anonymous::mock_storage#test_0001_raises when creating a bucket without authentication [test/google/cloud/storage/project_anonymous_test.rb:30]:
[Google::Cloud::UnauthenticatedError] exception expected, not
Class: <NoMethodError>
Message: <"undefined method `_' for #<Object:0x00007fae658703c8>">
---Backtrace---
test/google/cloud/storage/project_anonymous_test.rb:25:in `insert_bucket'
/Users/yahonda/src/github.com/googleapis/google-cloud-ruby/google-cloud-storage/lib/google/cloud/storage/service.rb:98:in `block in insert_bucket'
/Users/yahonda/src/github.com/googleapis/google-cloud-ruby/google-cloud-storage/lib/google/cloud/storage/service.rb:631:in `execute'
/Users/yahonda/src/github.com/googleapis/google-cloud-ruby/google-cloud-storage/lib/google/cloud/storage/service.rb:97:in `insert_bucket'
/Users/yahonda/src/github.com/googleapis/google-cloud-ruby/google-cloud-storage/lib/google/cloud/storage/project.rb:379:in `create_bucket'
test/google/cloud/storage/project_anonymous_test.rb:30:in `block (3 levels) in <main>'
---------------

2 runs, 2 assertions, 2 failures, 0 errors, 0 skips
%
```

2 Revert false positives of `google-cloud-storage/test/google/cloud/storage/project_anonymous_test.rb

```
% bundle exec ruby -w -Itest test/google/cloud/storage/project_anonymous_test.rb -n /test_0006_downloads/
... snip ...

  1) Failure:
Google::Cloud::Storage::Project::anonymous::mock_storage#test_0006_downloads a public file [test/google/cloud/storage/project_anonymous_test.rb:125]:
Expected #<Tempfile:/var/folders/4d/1hfsdkkj2772brj5d70vtbm40000gn/T/google-cloud20200410-6349-nvppgj> to be a kind of File, not Tempfile.

1 runs, 1 assertions, 1 failures, 0 errors, 0 skips
%
```

* Reverting auto-correct generates these warnings as expected.

```
DEPRECATED: global use of must_be_kind_of from /Users/yahonda/.rbenv/versions/2.6.6/lib/ruby/2.6.0/delegate.rb:83. Use _(obj).must_be_kind_of instead. This will fail in Minitest 6.
```